"use client"
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";


import TemporaryDrawer from "@/components/TemporaryDrawer";
import SideBarProvider, { SideBarContext } from "@/context/SideBarContext";



const montserrat = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	

	return (
		<html lang="en">
			<body className={montserrat.className}>
				<section className="bg-[#ededed]">
					{/* wrapp everything with my side bar */}
					<SideBarProvider>
							<TemporaryDrawer />
							{children}
					</SideBarProvider>
					
				</section>
			</body>
		</html>
	);
}
